#!/usr/bin/env bash
# add public key to server

USER="ubuntu"
SERVER="54.209.217.152"
PUB_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNdtrNGtTXe5Tp1EJQop8mOSAuRGLjJ6DW4PqX4wId/Kawz35ESampIqHSOTJmbQ8UlxdJuk0gAXKk3Ncle4safGYqM/VeDK3LN5iAJxf4kcaxNtS3eVxWBE5iF3FbIjOqwxw5Lf5sRa5yXxA8HfWidhbIG5TqKL922hPgsCGABIrXRlfZYeC0FEuPWdr6smOElSVvIXthRWp9cr685KdCI+COxlj1RdVsvIo+zunmLACF9PYdjB2s96Fn0ocD3c5SGLvDOFCyvDojSAOyE70ebIElnskKsDTGwfT4P6jh9OBzTyQEIS2jOaE5RQq4IB4DsMhvbjDSQrP0MdCLgwkN"

# Function to add the public key to authorized_keys
ssh "$USER@$SERVER" "mkdir -p ~/.ssh && chmod 700 ~/.ssh && echo $PUB_KEY >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys"
echo "Public key added to $USER@$SERVER"
